Document: Add SMBIOS additional Information for LoongArch
loongson/LoongArch-Documentation pull request #34
Opened 2021-12-14 12:38 UTC by kilaterlee

There is no standard table in the Type 44 in section 7.45 of SMBIOS.
It needs an external table to describe the additional information.

2021-12-14 13:08 UTC, FreeFlyingSheep commented
The script will copy HTMLs and PDFs from the `docs` folder, but will not traverse the subfolders.
Either move `docs/LoongArch-SMBIOS/LoongArch-SMBIOS-Additional-Information-EN.adoc` to `docs/LoongArch-SMBIOS-Additional-Information-EN.adoc`, or create a new file containing `include::LoongArch-SMBIOS/LoongArch-SMBIOS-Additional-Information-EN.adoc[]` in `docs`.
In addition, please add a link in `docs/README-CN.adoc`, otherwise we won't be able to see the new document on the [preview website](https://loongson.github.io/LoongArch-Documentation-Preview/).

2021-12-15 02:40 UTC, kilaterlee commented
@chenhuacai @yetist @ChenghuaXu @bibo-mao @qiandongyan 
各位来review一下，这个document是要当做SMBIOS的一个补充文档用的

2021-12-15 06:28 UTC, qiandongyan approved these changes

2021-12-15 06:51 UTC, yetist commented
预览页面在这里，建议在英文首页加上链接：
https://loongson.github.io/LoongArch-Documentation-Preview/LoongArch-SMBIOS-Additional-Information-EN.html

2021-12-16 04:44 UTC, xen0n requested changes

2021-12-16 04:44 UTC, xen0n commented on docs/README-CN.adoc
> +* 龙芯架构SMBIOS附加信息: 该手册描述了龙芯架构的附加信息。
首先新加的文档不是手册，其次通篇也没看出来哪里和 SMBIOS 产生了强的联系，链接到的文档名字带 SMBIOS 但自己标题里却没带。

2021-12-16 04:44 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +The LoongArch CPU designed by Loongson has two registers representing Machine Vendor Name and CPU Name, both of which are ASCII string values in DQWORD-formatted, respectively located at offsets 0x10
DQWORD 是啥，“双四字”，我印象中不是要么 DWORD 要么 QWORD 吗？

另外，“IOCSR”的 R 就是 register 的意思，不需要冗余写“IOCSR register”。这里实际要表达的意思是“IOCSR 地址空间”，而不是单个寄存器（单个寄存器哪来 0x20 这么宽），所以应该写“IOCSR space”。

2021-12-16 04:44 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +|Length of Processor-specific Data
这边不用 title-case 吧，首字母大写就行了

2021-12-16 04:44 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +|Vendor ID of this LoongArch processor manufacturer.
句子有点问题，感觉是不是直接写“Vendor ID of the processor”就够了？

2021-12-16 04:44 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +|The CPU ID used for this LoongArch processor manufacturer to mark different CPU types or CPU instances.
名字不考虑起个“Processor ID”跟 LA 手册里提到的 CPUCFG PRID 域命名保持一致吗？

另外后边的解释，感觉既多余又矛盾：多余是指的如果这个字段其实就是冗余一份 CPUCFG PRID，那不需要在这里重复讲解一遍语义，矛盾是指 PRID 字段目前在真实硬件（如 3A5000）上没有设计为产品唯一 ID，软件上也没有这么认为，所以实际上该字段的语义根本不可能实现为文中“or”的语义而只能取其一。

2021-12-16 04:44 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +Any bit of this field is set to 1, indicating that the corresponding extension is supported, and 0 indicates not supporting.
上面已经提了和 EUEn 字段语义一致了，这句解释就可以去掉了。

2021-12-16 04:44 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-CN.adoc
> +=== LoongArch Processor-specific Block Structure介绍
起英语标题是为了和什么规范文档保持一致吗？

2021-12-16 04:44 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-CN.adoc
> +|Processor-specific数据结构长度。
同上，如果没有特别的理由，建议翻译。

2021-12-16 04:44 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-CN.adoc
> +|Varies
既然这条记录写的偏移量是 01h，下面一条是 02h，那这个长度为啥是可变的而不是 1？其他地方也有同样问题。

2021-12-16 04:44 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-CN.adoc
> +|N BYTEs
同上，显然这个数据结构只有 1 字节长，否则下面那条记录就不能起始在 03h 了，至少有一处描述是错误的。

2021-12-16 04:50 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-CN.adoc
> +|类型
根据 SMBIOS 规范文档的写法，这里应该不是“类型”而是“取值”。。

2021-12-16 06:08 UTC, kilaterlee commented on docs/README-CN.adoc
> +* 龙芯架构SMBIOS附加信息: 该手册描述了龙芯架构的附加信息。
补丁描述里面提到了，我建议你看看SMBIOS specification，哪些DQWORD是按照他的风格写的

2021-12-16 06:08 UTC, kilaterlee commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +The LoongArch CPU designed by Loongson has two registers representing Machine Vendor Name and CPU Name, both of which are ASCII string values in DQWORD-formatted, respectively located at offsets 0x10
好的，这个确实表达不严谨

2021-12-16 06:09 UTC, kilaterlee commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +|The CPU ID used for this LoongArch processor manufacturer to mark different CPU types or CPU instances.
PRID那个域是架构的，跟CPU不是一个维度的，从英语的Processor和CPU的意义来看，我觉得Processor应该是CPU同级别的

2021-12-16 06:11 UTC, kilaterlee commented on docs/LoongArch-SMBIOS-Additional-Information-CN.adoc
> +=== LoongArch Processor-specific Block Structure介绍
refer SMBIOS section 7.45, Type44

2021-12-16 06:15 UTC, kilaterlee commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +Any bit of this field is set to 1, indicating that the corresponding extension is supported, and 0 indicates not supporting.
EUEN的语义是启用与否，这个是支持与否

2021-12-16 06:50 UTC, kilaterlee commented
@xen0n 考虑到SPEC不需要CN的，我提个patch把CN的去掉吧

2021-12-16 07:09 UTC, xen0n commented
> 

我看你上面大量提及 SMBIOS 原始文档，我确认下你提交这文档的意图是在上游规范文档没更新之前，给下游厂商一个参考？如果是这样的话可以去掉中文版（并且在中文版的首页里链接到英文文档，提一嘴为啥是 English-only 的）。否则按照常识，默认肯定以中文文档为权威，英文版作翻译，只是为了方便不懂汉语的人罢了。

2021-12-16 07:11 UTC, xen0n commented
> > 考虑到SPEC不需要CN的，我提个patch把CN的去掉吧
> 
> 我看你上面大量提及 SMBIOS 原始文档，我确认下你提交这文档的意图是在上游规范文档没更新之前，给下游厂商一个参考？如果是这样的话可以去掉中文版（并且在中文版的首页里链接到英文文档，提一嘴为啥是 English-only 的）。否则按照常识，默认肯定以中文文档为权威，英文版作翻译，只是为了方便不懂汉语的人罢了。

另外如果是这种情况，你英文文档开头也建议写一下“本文档应被理解为 SMBIOS vXX.XX 规范文档的补充”这样，否则整篇文档的行文不像是独立成文的文章，读着非常别扭，很多术语、缩略语也没有援引解释。

2021-12-16 07:31 UTC, kilaterlee commented
> > > 考虑到SPEC不需要CN的，我提个patch把CN的去掉吧
> > 
> > 
> > 我看你上面大量提及 SMBIOS 原始文档，我确认下你提交这文档的意图是在上游规范文档没更新之前，给下游厂商一个参考？如果是这样的话可以去掉中文版（并且在中文版的首页里链接到英文文档，提一嘴为啥是 English-only 的）。否则按照常识，默认肯定以中文文档为权威，英文版作翻译，只是为了方便不懂汉语的人罢了。
> 
> 另外如果是这种情况，你英文文档开头也建议写一下“本文档应被理解为 SMBIOS vXX.XX 规范文档的补充”这样，否则整篇文档的行文不像是独立成文的文章，读着非常别扭，很多术语、缩略语也没有援引解释。

这个文档其实是给SMBIOS type 44里面做补充文档用的，这个是提给上游的时候一个附加文档，因为Type44没有标准表项，而且看起来DMTF对于这个type有一定的灵活性，所以允许做一个类似于私有的table

2021-12-16 08:54 UTC, kilaterlee commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +|Vendor ID of this LoongArch processor manufacturer.
修改了

2021-12-16 09:42 UTC, kilaterlee commented
@loongson/edk2 @loongson/dev-team 来review啊...

2021-12-20 06:12 UTC, sterling-teng approved these changes
Great!

2021-12-20 09:36 UTC, qiandongyan approved these changes

2021-12-24 03:07 UTC, EricGao2015 commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +The LoongArch CPU designed by Loongson has two registers representing Machine Vendor Name and CPU Name, both of which are ASCII string values in DQWORD-formatted(SMBIOS uses 16 bits as a WORD, total
这行最后一个单词是space?

2021-12-24 03:11 UTC, kilaterlee commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +The LoongArch CPU designed by Loongson has two registers representing Machine Vendor Name and CPU Name, both of which are ASCII string values in DQWORD-formatted(SMBIOS uses 16 bits as a WORD, total
眼尖，我改改

2021-12-24 05:52 UTC, xen0n requested changes
按照 [riscv-smbios](https://github.com/riscv/riscv-smbios) 的实践经验，Type 4 可能也要改。文档标题我给了个修改建议，看下文件名、readme 链接这种你们自己也改掉

2021-12-24 05:52 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +The LoongArch CPU designed by Loongson has two registers representing Machine Vendor Name and CPU Name, both of which are ASCII string values in DQWORD-formatted(SMBIOS uses 16 bits as a WORD, total
`The LoongArch CPU designed by Loongson has two registers representing Machine Vendor Name and CPU Name`，那非龙芯公司设计的 LoongArch CPU 行为如何？

另外这一行的括号前面要加一个空格

2021-12-24 05:52 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +This document is used to describe additional information about the LoongArch processor of SMBIOS Type 44(Type 44 added after SMBIOS v3.3.0).
这个句子非常中式英语，帮你改了下：

```suggestion
This document defines the LoongArch processor-specific data block to supplement the upstream definition of SMBIOS structure Type 44 (Processor Additional Information, Section 7.45 of SMBIOS 3.5.0 specification).
```

2021-12-24 05:52 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +|DQWORD
我查证了 [SMBIOS 规范文档](https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.5.0.pdf)，确认不存在 `DQWORD` 的写法，应该用 `QWORD` 表示“64 位”。请修改一下。

2021-12-24 05:52 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +It is equivalence to IOCSR space offset 0x10 on a Loongson CPU.
```suggestion
Equal to the value located at IOCSR space offset 0x10.
```

这边把“在龙芯 CPU”几个字先去了，需要根据前面提到的在非龙芯设计的 LoongArch 处理器上行为如何的结论来更新这边的措辞。

2021-12-24 05:52 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +It is equivalence to IOCSR space offset 0x20 on a Loongson CPU.
同上

2021-12-24 05:52 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +|Extended instruction set support
```suggestion
|ISA extensions support
```

2021-12-24 05:52 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +|The bit field [3:0] encodes the existing LoongArch standard extensions instruction set. It equivalent to bits [3:0] in LoongArch EUEN register(CSR 0x2). +
```suggestion
|The bit field [3:0] indicate support for the existing LoongArch ISA extensions. It is modeled after the LoongArch EUEN register (CSR 0x2), and meanings of individual bits is the same as defined for the EUEN register. +
```

2021-12-24 05:52 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +Any bit of this field is set to 1, indicating that the corresponding extension is supported, and 0 indicates not supporting.
```suggestion
The corresponding bit is set for every ISA extension supported on this system.
```

2021-12-24 05:52 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> += LoongArch Processor Additional Information
Change to be more like the [riscv-smbios](https://github.com/riscv/riscv-smbios) project:

```suggestion
= LoongArch Processor SMBIOS Spec
```

2021-12-24 06:15 UTC, kilaterlee commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +The LoongArch CPU designed by Loongson has two registers representing Machine Vendor Name and CPU Name, both of which are ASCII string values in DQWORD-formatted(SMBIOS uses 16 bits as a WORD, total
这个是架构外的，使用LoongArch指令集完成的实例我们不保证他们会完成IOCSR或者IOCSR和龙芯设计的一样

2021-12-24 06:17 UTC, kilaterlee commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +|DQWORD
您已经查到RV的规范了，不妨看看他们的写法，我也是仿照他们的写的DQWORD :)
https://github.com/riscv/riscv-smbios/blob/master/riscv-smbios.pdf

2021-12-24 06:20 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +The LoongArch CPU designed by Loongson has two registers representing Machine Vendor Name and CPU Name, both of which are ASCII string values in DQWORD-formatted(SMBIOS uses 16 bits as a WORD, total
> 这个是架构外的，使用LoongArch指令集完成的实例我们不保证他们会完成IOCSR或者IOCSR和龙芯设计的一样

但这份文档应该对那些采用非龙芯公司 LoongArch CPU 设计的板卡也适用，可能还是要微调一下措辞，明确无论具体 CPU 对这些寄存器的实现如何，此处假定参照的是龙芯设计 CPU 的行为。

2021-12-24 06:21 UTC, kilaterlee commented
> 按照 [riscv-smbios](https://github.com/riscv/riscv-smbios) 的实践经验，Type 4 可能也要改。文档标题我给了个修改建议，看下文件名、readme 链接这种你们自己也改掉

是的，SMBIOS的specification提案已经写完了，这个属于附加规范，我需要在规范里面引用这个，所以要先评审这个，然后提CR给DMTF

2021-12-24 06:26 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +|DQWORD
由于上游规范文档里没提，RV 规范跟我们这篇是平级的，不妨单独弄一小节解释 DQWORD 这东西？我反正真的找了大半天 🤦

2021-12-24 06:32 UTC, kilaterlee commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +The LoongArch CPU designed by Loongson has two registers representing Machine Vendor Name and CPU Name, both of which are ASCII string values in DQWORD-formatted(SMBIOS uses 16 bits as a WORD, total
好的，我一会儿修改一下您再帮忙review一下

2021-12-24 06:33 UTC, kilaterlee commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +|DQWORD
要不然就不提DQWORD，就写two QWORD也可以，上游有这么写的

2021-12-24 06:34 UTC, kilaterlee commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +It is equivalence to IOCSR space offset 0x10 on a Loongson CPU.
这个还是根据上面提到的，如果修改措辞后还是要写"on a Loongson CPU"，类似于"on a AMD CPU"一个意思

2021-12-24 06:45 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +It is equivalence to IOCSR space offset 0x10 on a Loongson CPU.
了解，当然考虑到“龙芯”一词承载的太多意义，这里改成`on a Loongson-designed CPU` 或者 `on a CPU designed by Loongson` 这样好像也差不多，你们自己斟酌一下

2021-12-24 06:46 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +|DQWORD
那怎么清晰怎么来呗，我的建议是尽量往上游而不是 RV 靠（因为 RV 文档跟我们是平等的关系），但 DQWORD 在解释清楚的前提下更精炼也是事实。

2021-12-24 08:24 UTC, kilaterlee commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +It is equivalence to IOCSR space offset 0x10 on a Loongson CPU.
我感觉这里的Loongson就是特指Loongson设计的CPU，因为现在LoongArch和Loongson已经分开了，没什么歧义

2021-12-24 09:27 UTC, kilaterlee commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +The LoongArch CPU designed by Loongson has two registers representing Machine Vendor Name and CPU Name, both of which are ASCII string values in DQWORD-formatted(SMBIOS uses 16 bits as a WORD, total
其实这个措辞我想了想还是不用写，因为在下面的表里面已经提到了，在龙芯设计的CPU等价于这两个寄存器，否则表格提到的两个域就是来给CPU manufacturer来用的，这小节就是介绍了龙芯设计的CPU里面有两个寄存器来表征相关信息的。

2021-12-24 11:12 UTC, xen0n commented on docs/LoongArch-SMBIOS-Additional-Information-EN.adoc
> +The LoongArch CPU designed by Loongson has two registers representing Machine Vendor Name and CPU Name, both of which are ASCII string values in DQWORD-formatted(SMBIOS uses 16 bits as a WORD, total
那我感觉实际上不用特意强调和 LA 这俩寄存器的联系。。龙芯自己怎么设计 CPU 和自己的板卡，是龙芯的实现细节，标准不用去管（这边的 manufacturer 和 model 字串要不要跟 CPU 里存在的串保持一致是板卡厂商自己的事）

这种情况建议删掉绝大多数文字，包括这一节（在 SMBIOS 规范补充文档里出现“寄存器”的章节很奇怪，仿佛是 SMBIOS 规范要修补 LoongArch 架构文档一样），至多加入“如果 CPU 实现了 IOCSR 0x10/0x20 则建议此处取值与 CPU IOCSR 读出值保持一致”就好了，非常精炼。

2021-12-27 08:36 UTC, xen0n reviewed
这一轮主要是英语问题，另外仍然建议在中文的文档首页加上一个链接（注明 English-only），这样看中文的人不会忽视这么一篇文档。

2021-12-27 08:36 UTC, xen0n commented on docs/LoongArch-Processor-SMBIOS-Spec-EN.adoc
> +128-bits (In the SMBIOS specification, WORD is 16-bits, DWORD is 32-bits ,and QWORD is 64-bits).
```suggestion
128-bits (In the SMBIOS specification, WORD is 16-bits, DWORD is 32-bits, and QWORD is 64-bits).
```

2021-12-27 08:36 UTC, xen0n commented on docs/LoongArch-Processor-SMBIOS-Spec-EN.adoc
> +This document defines LoongArch processor-specific data block to supplement the upstream definition of SMBIOS structure Type 44 (Processor Additional Information, SMBIOS 3.5.0 or later specification
```suggestion
This document defines the LoongArch processor-specific data block to supplement the upstream definition of SMBIOS structure Type 44 (Processor Additional Information, section 7.45 in SMBIOS specification 3.5.0 or later).
```

2021-12-27 08:36 UTC, xen0n commented on docs/LoongArch-Processor-SMBIOS-Spec-EN.adoc
> +The LoongArch CPU designed by Loongson has two registers representing Machine Vendor Name and CPU Name, both of which are ASCII string values in DQWORD-formatted, respectively located at offsets 0x10
```suggestion
The LoongArch CPUs designed by Loongson have two registers representing Machine Vendor Name and CPU Name, both of which are DQWORD-format NUL-terminated ASCII string values, located at offsets 0x10 and 0x20 of the IOCSR space respectively.
```

2021-12-27 08:36 UTC, xen0n commented on docs/LoongArch-Processor-SMBIOS-Spec-EN.adoc
> +It is equal to the value at the offset 0x10 of the IOCSR space on a Loongson CPU.
强调下只是语义等价，这样可以给非龙芯公司的方案充足的自由度，也不至于影响互操作性：

```suggestion
It is semantically equivalent to the value at the offset 0x10 of the IOCSR space on a Loongson CPU.
```

2021-12-27 08:36 UTC, xen0n commented on docs/LoongArch-Processor-SMBIOS-Spec-EN.adoc
> +It is equal to the value at the offset 0x20 of the IOCSR space on a Loongson CPU.
同上

2021-12-27 08:36 UTC, xen0n commented on docs/LoongArch-Processor-SMBIOS-Spec-EN.adoc
> +|The bit field [3:0] indicate support for the existing LoongArch standard ISA extensions. It is modeled on the LoongArch EUEN register (CSR 0x2), and meanings of each bits is the same as defined for
`model after` 是固定搭配，另外还有其他的单复数问题

```suggestion
|The bit field [3:0] indicates support for the existing LoongArch standard ISA extensions. It is modeled after the LoongArch EUEN register (CSR 0x2), and meaning of each bit is the same as defined for the EUEN register. +
```

2021-12-27 08:36 UTC, xen0n commented on docs/LoongArch-Processor-SMBIOS-Spec-EN.adoc
> +Any bit of this field is set, indicating that the corresponding ISA extension is supported on this system.
这个句子翻译过来是“这个位域的任何位都（已经）置位了”，意思不对了。需要改一下。

```suggestion
A set bit means its corresponding ISA extension is supported on this system.
```

2021-12-28 06:45 UTC, kilaterlee commented on docs/LoongArch-Processor-SMBIOS-Spec-EN.adoc
> +The LoongArch CPU designed by Loongson has two registers representing Machine Vendor Name and CPU Name, both of which are ASCII string values in DQWORD-formatted, respectively located at offsets 0x10
这里是第三人称吧，用have不合适吧

2021-12-28 06:59 UTC, xen0n commented on docs/LoongArch-Processor-SMBIOS-Spec-EN.adoc
> +The LoongArch CPU designed by Loongson has two registers representing Machine Vendor Name and CPU Name, both of which are ASCII string values in DQWORD-formatted, respectively located at offsets 0x10
这里要表示的是适用 **所有** 龙芯公司设计的 LoongArch CPU，因此要用复数符合表达习惯

2021-12-29 06:36 UTC, xen0n reviewed
这一波改完我就没什么问题了 :+1:

2021-12-29 06:36 UTC, xen0n commented on docs/LoongArch-Processor-SMBIOS-Spec-EN.adoc
> +It is semantically qeuivalent to the value at the offset 0x10 of the IOCSR space on a Loongson CPU.
```suggestion
It is semantically equivalent to the value at the offset 0x10 of the IOCSR space on a Loongson CPU.
```

2021-12-29 06:36 UTC, xen0n commented on docs/README-CN.adoc
> +* 龙芯架构SMBIOS规范：该文档介绍了龙芯架构处理器附加信息，是SMBIOS type 44的补充。本文档仅提供 *英文版*。
加了几个空格调整了几个字

```suggestion
* 龙芯架构 SMBIOS 规范：该文档定义了龙芯架构的处理器相关附加信息，是 SMBIOS 结构 type 44 的补充。本文档仅提供 *英文版*。
```

2022-01-13 06:11 UTC, xen0n approved these changes
LGTM :+1:

2022-01-13 08:27 UTC, kilaterlee commented
> LGTM +1

来个approving呗

2022-01-13 08:32 UTC, xen0n commented
> > LGTM +1
> 
> 来个approving呗

这个组织的成员应该都是龙芯员工，我不是，不过我可以帮你 at 人：@FreeFlyingSheep @EricGao2015

2022-01-13 08:37 UTC, FreeFlyingSheep approved these changes

2022-01-13 08:37 UTC, merged